language: c

env:
    matrix:
        - python=3.3
        - python=3.4

install:
    # Get miniconda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    - bash Miniconda-latest-Linux-x86_64.sh -b
    - export PATH=$HOME/miniconda/bin:$PATH

    # Install requirements
    - conda config --add channels http://conda.binstar.org/omnia
    - conda create --yes -n test python=$python `cat requirements.txt | xargs`
    - source activate test

    # Get git version of mixtape
    - git clone git@github.com:rmcgibbo/mixtape.git $HOME/mixtape
        && conda install --yes cython scikit-learn
        && cd $HOME/mixtape
        && git fetch origin
        && git checkout -b 0.2 origin/0.2
        && python setup.py install
        && cd -

    - python setup.py install


script:
    - ipcluster start --n=2 --daemonize && sleep 5s
    - ./run_tests.sh -vv

after_success:
    - ipcluster stop
